export const assets = {
  gnb: {
    logoMark: "/assets/figma/gnb-logo-mark.png",
    logoType: "/assets/figma/gnb-logo-type.png",
    iconSun: "/assets/figma/gnb-icon-sun.svg",
    iconMoon: "/assets/figma/gnb-icon-moon.svg",
    iconMenuTablet: "/assets/figma/gnb-menu.svg",
    iconMenuMobile: "/assets/figma/gnb-menu-mobile.svg",
    iconClose: "/assets/figma/gnb-close.svg",
  },
  hero: {
    appLogo: "/assets/figma/hero-app-logo.png",
    iconApple: "/assets/figma/hero-icon-apple.svg",
    iconWindows: "/assets/figma/hero-icon-windows.svg",
    mock: "/assets/figma/hero-mock.webp",
    tabletMock: "/assets/figma/hero-tablet-mock.webp",
    mobileMock: "/assets/figma/hero-mobile-mock.webp",
  },
  why: {
    bg: "/assets/figma/why-bg.webp",
    tabletBg: "/assets/figma/why-bg-tablet.webp",
    mobileBg: "/assets/figma/why-bg-mobile.webp",
  },
  keypoints: {
    kp1: "/assets/figma/keypoint-1.webp",
    kp2: "/assets/figma/keypoint-2.webp",
    kp3: "/assets/figma/keypoint-3.webp",
    kp4: "/assets/figma/keypoint-4.webp",
    kp4Notif: "/assets/figma/keypoint-4-notif.png",
    kp5Min: "/assets/figma/keypoint-5-min.webp",
    kp5Med: "/assets/figma/keypoint-5-med.webp",
    tabletKp1: "/assets/figma/keypoint-t-1.webp",
    tabletKp2: "/assets/figma/keypoint-t-2.webp",
    tabletKp3: "/assets/figma/keypoint-t-3.webp",
    tabletKp4: "/assets/figma/keypoint-t-4.webp",
    tabletKp4Notif: "/assets/figma/keypoint-t-4-notif.png",
    tabletKp5Min: "/assets/figma/keypoint-t-5-min.webp",
    tabletKp5Med: "/assets/figma/keypoint-t-5-med.webp",
    mobileKp1: "/assets/figma/keypoint-m-1.webp",
    mobileKp2: "/assets/figma/keypoint-m-2.webp",
    mobileKp3: "/assets/figma/keypoint-m-3.webp",
    mobileKp4: "/assets/figma/keypoint-m-4.webp",
    mobileKp4Notif: "/assets/figma/keypoint-m-4-notif.png",
    mobileKp5Min: "/assets/figma/keypoint-m-5-min.webp",
    mobileKp5Med: "/assets/figma/keypoint-m-5-med.webp",
  },
  features: {
    iconSeat: "/assets/figma/feature-icon-seat.svg",
    iconWidget: "/assets/figma/feature-icon-widget.svg",
    iconDashboard: "/assets/figma/feature-icon-dashboard.svg",
    iconAlert: "/assets/figma/feature-icon-alert.svg",
    iconDashboardMobile: "/assets/figma/feature-icon-dashboard-mobile.svg",
    iconAlertMobile: "/assets/figma/feature-icon-alert-mobile.svg",
  },
  faq: {
    iconMinus: "/assets/figma/faq-minus.svg",
    iconMinusTablet: "/assets/figma/faq-minus-tablet.svg",
    iconPlusTablet: "/assets/figma/faq-plus.svg",
    divider: "/assets/figma/faq-divider.svg",
    iconPlusMobile: "/assets/figma/faq-plus-mobile.svg",
    iconMinusMobile: "/assets/figma/faq-minus-mobile.svg",
    dividerMobile: "/assets/figma/faq-divider-mobile.svg",
  },
  cta: {
    bg: "/assets/figma/cta-bg.webp",
    tabletBg: "/assets/figma/cta-bg-tablet.webp",
    mobileBg: "/assets/figma/cta-bg-mobile.webp",
  },
  footer: {
    social: "/assets/figma/footer-social.png",
    socialMobile: "/assets/figma/footer-social-mobile.png",
  },
} as const;
